apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/sample-app/deployment.yaml
  - ../../../apps/sample-app/service.yaml
  - ../../../apps/sample-app/configmap.yaml
  - ../../../apps/sample-app/secret-placeholder.yaml
namespace: apps-prod
commonLabels:
  app.kubernetes.io/name: sample-app
  app.kubernetes.io/part-of: sample-platform
