apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: apps-prod
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-prod-quota
  namespace: apps-prod
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    pods: "200"
