apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secrets
  namespace: apps-prod
type: Opaque
stringData:
  DATABASE_URL: "postgres://MY_APP_DB_USER:MY_APP_DB_PASSWORD@my-db:5432/mydb"
  JWT_SIGNING_KEY: "CHANGE_ME_IN_SECRET_MANAGER"
